### ISSUE TITLE
containers fails with "exited  - code 1" - Raspberry Pi 5 (aarch64)

### ISSUE THREAD

**Issue by tamal-sen** [bluewave-labs/checkmate#1368]
**Describe the bug**
I am trying to spin up checkmate stack using the [docker-composer file](https://raw.githubusercontent.com/bluewave-labs/checkmate/refs/heads/master/Docker/dist/docker-compose.yaml) provided in quickstart guide with Portainer. All four containers fail to load and I am receiving the following error in the container log
`exec /docker-entrypoint.sh: exec format error`
I am trying to run it on my RPi5 with ARM Cortex-A76 CPU. I guess the docker image does not support aarch64 arch yet, maybe that's why? Would love to have some guidance for this.

Here is my docker-compose file (adjusted some ports)
```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    environment:
      UPTIME_APP_API_BASE_URL: "http://localhost:5000/api/v1"
    ports:
      - "3000:80"
      - "4343:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
```

**To Reproduce**
1. Run the docker-compose file on a system with aarch64 arch CPU

**Expected behavior**
Containers will run normally
