### ISSUE TITLE
"network error" cant login / register

### ISSUE THREAD

**Issue by audricd** [bluewave-labs/Checkmate#1734]
**Describe the bug**
Cannot register / use

**To Reproduce**

1. Setup on remote server, download this [yml](https://github.com/bluewave-labs/bluewave-uptime/raw/refs/heads/master/Docker/dist/docker-compose.yaml), and adapt it as such:
```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://server:5000/api/v1"
    #ports:
      #- "80:80"
      #- "443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    #ports:
      #- "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    #ports:
      #- "6379:6379"
    volumes:
      - /home/kireek/docker/checkmate/redis/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - /home/kireek/docker/checkmate/mongo/:/data/db
    command: ["mongod", "--quiet"]
    #ports:
      #- "27017:27017"                                  
networks:                                                  
  default:                                                 
    external:                                              
      name: ext
```
modifications explained:

- changed `UPTIME_APP_API_BASE_URL: "http://localhost:5000/api/v1"` to `UPTIME_APP_API_BASE_URL: "http://server:5000/api/v1"`, as the container hostname (should be?) is server, as per the service name in the stack
- unexpose the ports on the host because of:
- added network ext which is nginx's
2. in my register, made a new entry, subdomain, for this service
3. in nginx: added a new entry with:

![Image](https://github.com/user-attachments/assets/ff31a43a-c986-42df-bbf1-0f44a7c5bbf1)
I have also tried to expose all ports and go to serverip:80, but the behavior is exactly the same

After registering (manually going to /register) , I go to login (weirdly enough, I am not redirected to it. After clicking register, the register invite appears. again), and this error show up:

![Image](https://github.com/user-attachments/assets/cc67a14a-399b-43ee-b9b5-e6979e4166d0)

**Expected behavior**
As per this documentation: https://docs.checkmate.so/users-guide/troubleshooting#q-i-installed-checkmate-but-i-dont-see-the-registration-page-to-sign-up-for-the-first-time I should be redirected to the registration page. However, I am redirected to the login page.
Yet, I go to /register manually, fill in the fields, and I expected to be able to login, without the "network error" message

**Screenshots**
see above

**Desktop (please complete the following information):**
 - Latest Firefox and Vivaldi. From workstation and cellphone

**Comment by audricd** [comment]
Same happens with this compose file:
```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://checkmate-server-1:5000/api/v1"
    #ports:
      #- "80:80"
      #- "443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    #ports:
      #- "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://checkmate-mongodb-1:27017/uptime_db
      - REDIS_HOST=checkmate-redis-1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    #ports:
      #- "6379:6379"
    volumes:
      - /home/kireek/docker/checkmate/redis/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - /home/kireek/docker/checkmate/mongo/:/data/db
    command: ["mongod", "--quiet"]
    #ports:
      #- "27017:27017"                                  
networks:                                                  
  default:                                                 
    external:                                              
      name: ext   
```                    

![Image](https://github.com/user-attachments/assets/50656054-e1a8-4176-af18-9e7207f8e971)

**Comment by ajhollid** [comment]
The original docker configuration is correct.

Your Client is running in your browser, not your Docker network, using `server` as the host will not work.

If your server is running on the sane machine as your client then the host is `localhost`

**Comment by ajhollid** [comment]
On another note, I would try just using vanilla docker compose with the provided docker compose file and seeing if the problem is with portainer.

That will help narrow down the possibilities.

**Comment by audricd** [comment]
I see, thanks!

Well just sharing in case it can enlighten anyone else:

Following your advice, I have used the default compose file:
```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://localhost:5000/api/v1"
    ports:
      - "880:80"
      - "4443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/kireek/docker/checkmate/redis/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - /home/kireek/docker/checkmate/mongo/:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
```
They are only two modifications:

1. Default ports are already in use in my network, so I changed them (and of course, used them on nginx)
2. And changed the location for files. I use those directories for backup purposes

Unfortunately, the behavior is exactly the same. And the issue is not nginx: I have tried to register, and login through serverip:880, and same result.

So I am very confused. Default, with ports exposed, doesnt work either.

For the record, on paper, my modified compose should work:

```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://checkmate-server-1:5000/api/v1"
    #ports:
      #- "80:80"
      #- "443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    #ports:
      #- "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://checkmate-mongodb-1:27017/uptime_db
      - REDIS_HOST=checkmate-redis-1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    #ports:
      #- "6379:6379"
    volumes:
      - /home/kireek/docker/checkmate/redis/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - /home/kireek/docker/checkmate/mongo/:/data/db
    command: ["mongod", "--quiet"]
    #ports:
      #- "27017:27017"                                  
networks:                                                  
  default:                                                 
    external:                                              
      name: ext
```

Why? Because all containers can see each other with the hostname I have set:

![Image](https://github.com/user-attachments/assets/55bea1dc-90d7-4c95-8827-71891c5dc925)

![Image](https://github.com/user-attachments/assets/9666c125-8b63-4611-82f5-1f417cfc6588)

The other two containers do no have ping installed so I cannot troubleshoot in that direction

![Image](https://github.com/user-attachments/assets/4c52a805-ec6e-4e71-98e6-0ba61e21ed4a)

**Comment by ajhollid** [comment]
@audricd there is no issue with the Docker network, as I can see from your logs the Server is reaching the MongoDB docker container and connecting correctly.

The issue is between your Client, which is not in your Docker network, and the Server.

The server operates on a port, default 5000.  The Docker container _must_ expose this port, or the Client will not be able to connect to it.

If you change what ports/hosts your Server operates on you must update your configuration to reflect that.

You do not need to ping the Server container from the Client container.  All the Client container does is start an nginx instance that serves the Client application to your browswer.

To resolve this issue you need to find out why you cannot connect to your Server container from wherever your client is running.  In your case this is almost certainly your browser running on your local machine, so you should ping from your local machine to whatever host/port you've set your Server to operate on.  By default this is `localhost` on port 5000.

Hope that helps clarify what the issue is and helps you track it down.

**Comment by audricd** [comment]
hmmm
I must be facing something really weird, or missing something really obvious

I am taking down every step possible and doing everything as most out of the box possible.

I am ditching portainer all together.

![Image](https://github.com/user-attachments/assets/2d2b61da-1262-4d7c-92ac-1a573c193c1e)

![Image](https://github.com/user-attachments/assets/f9cb58a5-2591-4c7e-a949-6361d9668672)

```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://localhost:5000/api/v1"
    ports:
      - "880:80"
      - "4443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
```

I have ONLY set the ports for client on the host to 880 and 4443 instead of 80 and 443 because these are busy already.

I still get network error. And at the initial loading of the page, I am directed to login instead of register. 

is there anywhere in the code anything that makes that if the port number of the container and the host do not match to not work...? if so, I dont really get the point of having a docker solution.

they are still two things I fail to understand, despite sorry its obvious: I am not an expert:

1. why is it supposed to work as "localhost"? localhost is localhost within a host, within a container. If a host is supposed to be called from an another host, it should be called as either its hostname or ip. or container name, in the case of docker. 
2. refer to my first message. in the ready to go docker solution, how are emails sent? in "dev installation documentation, https://docs.checkmate.so/users-guide/quickstart#env-vars-server smtp server variables must be set. what is actually being used in the automatic installation?
