### ISSUE TITLE
Infrastructure page is blank

### ISSUE THREAD

**Issue by 4Benj** [bluewave-labs/Checkmate#1859]
**Describe the bug**

I have added an infrastructure monitor and after going to another page and going back to http://[checkmate_url]/infrastructure, the page is completely blank with the following errors in the console
index-CO2SgZMe.js:40 TypeError: Cannot read properties of undefined (reading 'uptimeGood')
    at index-CO2SgZMe.js:299:5226
    at Array.map (<anonymous>)
    at ade (index-CO2SgZMe.js:299:4614)
index-CO2SgZMe.js:299 Uncaught TypeError: Cannot read properties of undefined (reading 'uptimeGood')
    at index-CO2SgZMe.js:299:5226
    at Array.map (<anonymous>)

**To Reproduce**
1. Go to 'infrastructure'
2. Add a new infrastructure monitor
3. Navigate to another page
4. Go back to 'infrastructure'
4. See that the page is empty

**Expected behavior**
Should come up with a list of infrastructures that are being monitored

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: I have tried Chrome, Firefox, and Edge

**Additional context**

Based on the logs, there are no errors and the server seems to be still monitoring my infrastructure

**Comment by 4Benj** [comment]
I removed all monitors and readded my infrastructure monitor and it seems to be working perfectly fine now. I am not sure if I should close this or leave it open.

**Comment by gorkem-bwl** [comment]
Let's check this @4Benj anyways. Thanks for reporting this!

**Comment by ajhollid** [comment]
Hi @4Benj ,

If this happens again please post any logs that you can, that will help if there's an actual issue here.

Thanks for the report!

**Comment by 4Benj** [comment]
It looks like it happened again. 
Since my report, I have restarted the checkmate server (and the monitor), so it could be related.
The console in the browser is the same issue as my initial report and there doesn't seem to be any errors within the logs of any of the services.

**Comment by gorkem-bwl** [comment]
Thanks @4Benj for reporting - let's check this.

**Comment by noahstreller** [comment]
Same thing happening here; blank page for infrastructure monitors on Checkmate v2.0.2. In the debugger, the variable t.palette.percentage.uptimeGood seems to be problematic:

```js
{
		id: "actions",
		content: "Actions",
		render: j => h.jsx(sn, {
			children: h.jsx(eD, {
				monitor: j,
				isAdmin: e,
				updateCallback: C
			})
		})
	}]
	  , A = p.map(j => {
		var D, L, N, F, V, q;
		const T = ((((L = (D = j.checks[0]) == null ? void 0 : D.cpu) == null ? void 0 : L.usage_frequency) ?? 0) / 1e3).toFixed(2) + " GHz"
		  , _ = (((N = j == null ? void 0 : j.checks[0]) == null ? void 0 : N.cpu.usage_percent) ?? 0) * 100
		  , M = (((F = j == null ? void 0 : j.checks[0]) == null ? void 0 : F.memory.usage_percent) ?? 0) * 100
		  , E = (((q = (V = j == null ? void 0 : j.checks[0]) == null ? void 0 : V.disk[0]) == null ? void 0 : q.usage_percent) ?? 0) * 100
		  , O = x(j)
		  , R = (((j == null ? void 0 : j.uptimePercentage) ?? 0) * 100).toFixed(2).toString()
		  , I = j.uptimePercentage < .25 ? t.palette.error.main : j.uptimePercentage < .5 ? t.palette.percentage.uptimeFair : j.uptimePercentage < .75 ? t.palette.percentage.uptimeGood : t.palette.success.lowContrast; // here
		return {
			id: j._id,
			name: j.name,
			url: j.url,
			processor: T,
			cpu: _,
			mem: M,
			disk: E,
			status: O,
			uptimePercentage: R,
			percentageColor: I
		}
	}
	);
```

**Comment by Wanxp** [comment]
version: Checkmate v2.0.2
platform: ubuntu 24.04, docker 27.3.1
action: add current host `checkmate agent` to checkmate client from web


Mine is blank to ,here is frontend console logs:
```plaintext
Cannot read properties of undefined (reading 'uptimeGood')
    at index-CO2SgZMe.js:299:5226
    at Array.map (<anonymous>)
    at ade (index-CO2SgZMe.js:299:4614)
    at iS (index-CO2SgZMe.js:38:17018)
    at O3 (index-CO2SgZMe.js:40:3139)
    at $M (index-CO2SgZMe.js:40:44833)
    at _M (index-CO2SgZMe.js:40:39790)
    at bq (index-CO2SgZMe.js:40:39718)
    at T1 (index-CO2SgZMe.js:40:39570)
    at z3 (index-CO2SgZMe.js:40:35934)
```

**Comment by ajhollid** [comment]
Yep this should be resolved already, but we'll double check this

**Comment by MarioDeLeonRecinos** [comment]
Hello I am using the v2.1.1 and it's showing a similar behaviour that fixes itself after navigating the site 

![Image](https://github.com/user-attachments/assets/0ff03a93-bfa2-44e2-9196-cad72bc550b5)
It's not showing errors at the moment of the request and in the console

**Comment by ajhollid** [comment]
Hi @MarioDeLeonRecinos,

So it

1. Displays correct data
2. Stops displaying data
3. Displays data again after navigating away and returning?

Can you please describe how to reproduce the issue?

Thanks!

**Comment by MarioDeLeonRecinos** [comment]
The issue presents itself when leaves unattended for some hours like 5 it's the time that I saw and i didn't mentioned it before but I upgrade versions without a clean install I don't know if that too can be the cause in the behavior but it behaves like you described in the 3 steps

**Comment by MarioDeLeonRecinos** [comment]
I found my problem it was that in my docker compose I didn't have the new scheduler that is mentioned in latest versions of checkmate maybe it would be better to tag the images wit a version instead of using latest in the docker examples in the tagged branches

**Comment by MarioDeLeonRecinos** [comment]
i leave here the changed docker-compose if it is of any help to another person i made aditional changes to redis that checking the logs it had a conflict that make the same bug happen

```
services:
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=test
      - CLIENT_HOST=https://test.test.test
      - SYSTEM_EMAIL_PASSWORD=test
      - SYSTEM_EMAIL_ADDRESS=test@test.test
      - SYSTEM_EMAIL_PORT=465
      - SYSTEM_EMAIL_HOST=smtp.gmail.com
      - TOKEN_TTL=45d
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock:ro
  scheduler:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
#      - JWT_SECRET=test

  redis:
    image: ghcr.io/bluewave-labs/checkmate:redis-dist
    restart: always
    volumes:
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    command: ["redis-server", "--save", ""]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: ghcr.io/bluewave-labs/checkmate:mongo-dist
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
```
i didnt leave the front part that i'm using nginx already in that server and it creates conflicts with that nginx if i have it in another port i have an specfic directory with the code compiled for that part
