### ISSUE TITLE
Monitor sites showing inactive status

### ISSUE THREAD

**Issue by enact-on** [bluewave-labs/Checkmate#2020]
## Description
When adding sites to monitor through Checkmate, all sites (including reliable domains like google.com) show as inactive. Error logs show issues with the PageSpeed API integration.

## Error Messages
Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 67d94dda5a7b96023c9137c4)

## Environment
- Deployment method: Coolify
- PageSpeed API key: Added but encountering errors
- Sites tested: Multiple sites including google.com

## Steps to Reproduce
1. Deploy Checkmate through Coolify
2. Add PageSpeed API key to configuration
3. Add site to monitor (e.g., google.com)
4. Observe that site shows as inactive
5. Check logs and find errors related to lighthouseResult

## Additional Information
- All attempted sites show as inactive
- Error occurs consistently across different domains
- PageSpeed API key has been verified as correctly formatted

## Questions
- Is there a known issue with the PageSpeed API integration?
- Are there specific formatting requirements for URLs when adding sites?
- Could this be related to network connectivity from the Coolify deployment?

## Error Screenhsot:
- https://img.enacton.com/ShareX/2025/04/chrome_kV7CtMkPXr.png
- https://img.enacton.com/ShareX/2025/04/chrome_NuUCUkaz7L.png

**Comment by gorkem-bwl** [comment]
First of all, many thanks for your detailed issue. Appreciate the time and effort you put into this.

That is because the Google Page Speed API blocks our calls, so you need to create your own PageSpeed API and then add it to the .env file, or use as an environment variable. This wasn't so previously, hence we'll add a warning in that screen. In fact let me add this issue for the next release, so people won't be surprised.

Please find more information here: https://docs.checkmate.so/users-guide/quickstart#env-vars-server

Let me know if that works!

**Comment by nothingrandom** [comment]
Hey! Also have this same issue; I've already placed the PageSpeed API key I made into the environment variables.

```
2025-04-03T15:57:27.159656297Z 2025-04-03T15:57:27.158Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 67eeaf324602c3f9c175a0f3)
2025-04-03T15:58:02.811828845Z 2025-04-03T15:58:02.811Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 67eeb00a4602c3f9c175a125)
2025-04-03T16:00:27.111601812Z 2025-04-03T16:00:27.110Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 67eeaf324602c3f9c175a0f3)
2025-04-03T16:01:02.903038914Z 2025-04-03T16:01:02.902Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 67eeb00a4602c3f9c175a125)
```

I've got two checks here; and have waited for the first 3 minute check to see if it was just an initial setup issue.

The env variable has been setup the way described in the docs, and if in the termianl of the server instance I check by doing `echo $PAGESPEED_API_KEY` I get the key details I expect.

**Comment by ajhollid** [comment]
Hi @nothingrandom ,

Could you please let us know how you are running the application?  Are you using docker compose?  Or local dev environment?

The pagespeed API key needs to be set in either the server directorie's `.env` file if you are running the local dev server or in the docker compose file if you are using docker compose.

**Comment by enact-on** [comment]
Hello @gorkem-bwl 

We have deployed through Coolify and  we are running through docker and we have created and added the pagespeed key in .env file, but the issue persists

Please ref to the image attached

![Image](https://github.com/user-attachments/assets/75a95f39-8290-4256-a083-59a068429040)

Thanks

**Comment by gorkem-bwl** [comment]
> Hello [@gorkem-bwl](https://github.com/gorkem-bwl) [@ajhollid](https://github.com/ajhollid)
> 
> We have deployed through Coolify and we are running through docker and we have created and added the pagespeed key in .env file, but the issue persists
> 
> Please ref to the image attached
> 
> ![Image](https://github.com/user-attachments/assets/75a95f39-8290-4256-a083-59a068429040)
> 
> Thanks

Thanks for this. I believe other env variables work, is that right? Also CC'ing @ajhollid here.

**Comment by sudo-eugene** [comment]
I'm also having this issue.

docker compose logs:
```
server-1   | 2025-04-16T12:19:08.857Z error: [StatusService](insertCheck) Cannot read properties of undefined (r
```

I'm running the instance locally with docker-compose. Here's my docker compose file:
Note: i've added the PAGESPEED_API_KEY under both server and client in an effort to try and debug this
```
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: ${UPTIME_APP_API_BASE_URL}
      VITE_APP_API_BASE_URL: ${UPTIME_APP_API_BASE_URL}
      PAGESPEED_API_KEY: 'A...k'
    ports:
      - "808:80"
      - "433:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    ports:
      - "5050:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
      - PAGESPEED_API_KEY=A...k
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
```


I did a docker exec into the server with `docker exec -it checkmate-server-1 /bin/sh` and ran `/app # printenv | grep PAGESPEED_API_KEY` to get the following result successfully:
```
PAGESPEED_API_KEY=A...
```
