### ISSUE TITLE
Client container wont start

### ISSUE THREAD

**Issue by tiberio87** [bluewave-labs/Checkmate#2124]
My client container does not start, from this error: host not found in upstream "server" in /etc/nginx/conf.d/default.conf:19

On my docker host ipv6 is disable 

```
services:
  checkmate-client:
    image: bluewaveuptime/uptime_client:latest
    container_name: checkmate-client
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://192.168.178.20:5000/api/v1"
    ports:
      - "850:80"
      - "4466:443"
    depends_on:
      - checkmate-server
  checkmate-server:
    image: bluewaveuptime/uptime_server:latest
    container_name: checkmate-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - checkmate-redis
      - checkmate-mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://checkmate-mongodb:27017/uptime_db
      - REDIS_HOST=checkmate-redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  checkmate-redis:
    image: bluewaveuptime/uptime_redis:latest
    container_name: checkmate-redis
    restart: always
    ports:
      - "6125:6379"
    volumes:
      - $DOCKERDIR/appdata/checkmate/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  checkmate-mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    container_name: checkmate-mongodb
    restart: always
    volumes:
      - $DOCKERDIR/appdata/checkmate/db:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
```

```
2025/04/23 05:49:10 [emerg] 1#1: host not found in upstream "server" in /etc/nginx/conf.d/default.conf:19
nginx: [emerg] host not found in upstream "server" in /etc/nginx/conf.d/default.conf:19
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/env.sh
UPTIME_APP_API_BASE_URL=http://192.168.178.20:5000/api/v1
/docker-entrypoint.sh: Configuration complete; ready for start up
2025/04/23 05:50:10 [emerg] 1#1: host not found in upstream "server" in /etc/nginx/conf.d/default.conf:19
nginx: [emerg] host not found in upstream "server" in /etc/nginx/conf.d/default.conf:19
```
