### ISSUE TITLE
Google PageSpeed API integration fails despite valid API key

### ISSUE THREAD

**Issue by draatman** [bluewave-labs/Checkmate#2198]
The PageSpeed API key works when tested manually, but when used by the application, it fails to fetch and process the lighthouseResult from the API response.

To Reproduce

Set the PAGESPEED_API_KEY in the environment variables of the Docker container.

Add a PageSpeed monitor to the application.

Check the server logs after attempting to run the monitor.

See the error: Cannot read properties of undefined (reading 'lighthouseResult')

Expected behavior
The server should call the Google PageSpeed API and correctly process the lighthouseResult from the response, showing the monitor result.

Logs showing the error: Cannot read properties of undefined (reading 'lighthouseResult')

Additional context
The API key works when tested manually inside the container using the wget command, but fails when used by the application, indicating a potential issue with how the application handles the response.

**Comment by empiricompany** [comment]
I can confirm the same error occurs here too:

`2025-05-06T11:29:44.953015474Z 2025-05-06T11:29:44.952Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)`

**Comment by ajhollid** [comment]
@draatman @empiricompany this issue should be resolved in the latest release, please reopen if you have any further issues with it.  Thank you!

**Comment by empiricompany** [comment]
@ajhollid thanks, but i have updated docker image to latest version on coolify
![coolify](https://github.com/user-attachments/assets/4e6085e9-01f5-401c-a47f-d941f0df291a)
I set the API key in the environment variables, but it still doesn't work, and I don't see the new setting to configure the API key from the interface.
The error is still the same.

```
2025-05-15T21:18:34.766325810Z 2025-05-15T21:18:34.765Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)
2025-05-15T21:21:34.279315720Z 2025-05-15T21:21:34.277Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)
```

**Comment by empiricompany** [comment]
this is my docker-compose
```yml
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - SERVICE_FQDN_CHECKMATE_80
      - 'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - SERVICE_FQDN_CHECKMATESERVER_5000
      - 'JWT_SECRET=${SERVICE_PASSWORD_64_JWT}'
      - 'REFRESH_TOKEN_SECRET=${SERVICE_PASSWORD_64_REFRESH}'
      - 'SYSTEM_EMAIL_ADDRESS=${SYSTEM_EMAIL_ADDRESS:-test@example.com}'
      - 'SYSTEM_EMAIL_PASSWORD=${SERVICE_PASSWORD_64_EMAIL}'
      - 'SYSTEM_EMAIL_HOST=${SYSTEM_EMAIL_HOST}'
      - 'SYSTEM_EMAIL_PORT=${SYSTEM_EMAIL_PORT}'
      - 'PAGESPEED_API_KEY=${PAGESPEED_API_KEY}'
      - 'DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-mongodb://mongodb:27017/uptime_db}'
      - 'REDIS_HOST=${REDIS_HOST:-redis}'
      - 'REDIS_PORT=${REDIS_PORT:-6379}'
      - 'DB_TYPE=${DB_TYPE:-MongoDB}'
      - 'TOKEN_TTL=${TOKEN_TTL:-99d}'
      - 'REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-99d}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - redis
      - mongodb
  redis:
    image: 'bluewaveuptime/uptime_redis:latest'
    volumes:
      - 'redis:/data'
  mongodb:
    image: 'bluewaveuptime/uptime_database_mongo:latest'
    volumes:
      - 'mongodb:/data/db'
    command:
      - mongod
      - '--quiet'

```
