### ISSUE TITLE
Not a valid Container ID

### ISSUE THREAD

**Issue by jschaufuss** [bluewave-labs/Checkmate#2303]
**Describe the bug**
When creating a docker monitor it will not take the Container ID it just tells me it is not valid... but it is :( 

**To Reproduce**
1. Go to <Server>/uptime/create
2. Click on Docker Container Monitoring
3. Scroll down to Container ID
4. Enter Container ID
5. See error

**Expected behavior**
Connection to Container

**Screenshots**

![Image](https://github.com/user-attachments/assets/c2d5b565-5fbd-4f4f-a47b-e127c857ad72)

**Desktop (please complete the following information):**
 - Browser Firefox
 - Checkmate Client/Server Version = latest (just pulled it)

**Additional context**

Here is my Compose:

```
services:
  client:
    image: ghcr.io/bluewave-labs/checkmate:frontend-dist
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://192.168.1.109:52345/api/v1"
      UPTIME_APP_CLIENT_HOST: "http://192.168.1.109:8085"
    ports:
      - "8085:80"
      - "4430:443"
    depends_on:
      - server
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=http://192.168.1.109:8085
      - JWT_SECRET=IwontShowYou
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: ghcr.io/bluewave-labs/checkmate:redis-dist
    restart: always
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: ghcr.io/bluewave-labs/checkmate:mongo-dist
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --qu>
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
```
