### ISSUE TITLE
Frontend ignores API URL set via environment variables in Docker deployment

### ISSUE THREAD

**Issue by GitBib** [bluewave-labs/Checkmate#2305]
**Describe the bug**
When specifying my domain in the docker-compose.yml file for the frontend (client service), the frontend app does not use the provided domain in environment variables. Instead, it keeps using localhost as the API base URL and client host, despite the variables being set as described in the [Quickstart guide](https://docs.checkmate.so/users-guide/quickstart).
**Note:**
The service is accessed through my own Nginx reverse proxy, which forwards requests to the corresponding Docker container.

**To Reproduce**

Deploy the frontend (client service) using the following docker-compose.yml:

```yaml
services:
  client:
    image: ghcr.io/bluewave-labs/checkmate:frontend-dist
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://example.com/api/v1"
      UPTIME_APP_CLIENT_HOST: "http://example.com"
    ports:
      - "3441:80"
    depends_on:
      - server
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    # ...other settings
```
**Start the containers:**
`docker compose up -d`

Open the frontend in your browser at http://example.com

Open the network tab or check the requests

**Expected behavior**
The frontend should use the provided environment variables (UPTIME_APP_API_BASE_URL and UPTIME_APP_CLIENT_HOST) and make API requests to http://example.com, not to localhost.

**Example log snippet:**
```
client-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
client-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
client-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
client-1  | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
client-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
client-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
client-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
client-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/env.sh
client-1  | UPTIME_APP_API_BASE_URL=http://example.com/api/v1
client-1  | UPTIME_APP_CLIENT_HOST=http://example.com
client-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
client-1  | 2025/05/19 15:51:00 [notice] 1#1: using the "epoll" event method
client-1  | 2025/05/19 15:51:00 [notice] 1#1: nginx/1.27.1
client-1  | 2025/05/19 15:51:00 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
client-1  | 2025/05/19 15:51:00 [notice] 1#1: OS: Linux 5.15.0-140-generic
client-1  | 2025/05/19 15:51:00 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
client-1  | 2025/05/19 15:51:00 [notice] 1#1: start worker processes
client-1  | 2025/05/19 15:51:00 [notice] 1#1: start worker process 42
client-1  | 2025/05/19 15:51:00 [notice] 1#1: start worker process 43
client-1  | 2025/05/19 15:51:00 [notice] 1#1: start worker process 44
client-1  | 2025/05/19 15:51:00 [notice] 1#1: start worker process 45
```
I followed the instructions in [the documentation](https://docs.checkmate.so/users-guide/quickstart).

**Comment by gorkem-bwl** [comment]
Thank you for creating a detailed issue @GitBib - let's look at this.

**Comment by GitBib** [comment]
Here is a screenshot from the browser showing where the request is being sent.

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/a50fee1b-be84-480c-a598-4fcd2a8df6ef" />

**Comment by jschaufuss** [comment]
did you set  CLIENT_HOST=http://example.com in the docker server config ?

**Comment by ajhollid** [comment]
Hi @GitBib ,

I am unable to replicate this issue using the standard docker compose file in a clean environment.

```
services:
  client:
    image: ghcr.io/bluewave-labs/checkmate:frontend-dist
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://thisismyurl:52345/api/v1"
      UPTIME_APP_CLIENT_HOST: "http://localhost"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=http://localhost
      - JWT_SECRET=my_secret
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: ghcr.io/bluewave-labs/checkmate:redis-dist
    restart: always
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: ghcr.io/bluewave-labs/checkmate:mongo-dist
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

```

results in network requests as expected

![Image](https://github.com/user-attachments/assets/74356f68-39cc-49b3-a8a9-d798b386a94b)

I suggest trying the initial setup without altering the docker config file and see if you can verify all is working as expected, then make your changes incrementally unitl you find what is causing the issue

**Comment by jschaufuss** [comment]
@ajhollid 

He customized this two Values
UPTIME_APP_API_BASE_URL: "http://example.com/api/v1"
UPTIME_APP_CLIENT_HOST: "http://example.com"

But I think he forgot to Change the Default "CLIENT_HOST=http://localhost" in the Server Environment.
He has to change it to  "CLIENT_HOST=http://example.com" otherwise it will send requests to localhost

Faced the same Error because of this

**Comment by GitBib** [comment]
@ajhollid Yes, I changed both parameters because I’m proxying both the client and server through Nginx, since there are several statistics systems running on this machine. I’m attaching the full file below.

```yaml
services:
  client:
    image: ghcr.io/bluewave-labs/checkmate:frontend-dist
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://example.com/api/v1"
      UPTIME_APP_CLIENT_HOST: "http://example.com"
    ports:
      - "3441:80"
    depends_on:
      - server
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=https://example.com
      - JWT_SECRET=sIFiDz27Cz1A72UwjA66yzW6NQbaYMZ8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: ghcr.io/bluewave-labs/checkmate:redis-dist
    restart: always
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: ghcr.io/bluewave-labs/checkmate:mongo-dist
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
```

**Comment by GitBib** [comment]
I changed the format of the environment section in my file, and now the domain is picked up correctly. However, the protocol is still set to http instead of https, even though I specified https in the value.

Here’s the relevant part of my config:

```yaml
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      DB_CONNECTION_STRING: "mongodb://mongodb:27017/uptime_db?replicaSet=rs0"
      REDIS_URL: "redis://redis:6379"
      CLIENT_HOST: "https://example.com"
      JWT_SECRET: "token"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
