### ISSUE TITLE
Unable to create a user to start using the app

### ISSUE THREAD

**Issue by profucius** [bluewave-labs/Checkmate#2316]
**Describe the bug**
I just discovered your app and spun it up on my Proxmox machine within an LXC running Docker. I have other docker stacks/containers running beside of this successfully. However Checkmate seems to be erroring out and I cant create an account or login to use the app. It reports "server is unreachable" from the WebUI. The confusing thing to me is that the WebUI is reachable fine, so maybe its the DB that is failing? I can provide docker logs if necessary.

**To Reproduce**
1. Use my compose at the bottom of this ticket.
2. Try creating a new user account.
3. Get the network error.

**Expected behavior**
To be able to create an account and start using the service.

**Screenshots**
### Reach initial page fine:
![Image](https://github.com/user-attachments/assets/3d20baf5-1978-4a21-a272-788910342fe7)

### Click on "Register here", see this page fine:
![Image](https://github.com/user-attachments/assets/0ac80b11-fe77-4af0-9b7f-40cc88cc398c)

### Three seconds later, page changes itself to this:
![Image](https://github.com/user-attachments/assets/6c2b368e-2928-4b17-bdea-eeaa2d5b4c27)

### Click "Retry connection" and it says server is unreachable:
![Image](https://github.com/user-attachments/assets/42841986-76e4-4a3f-a5b9-9ab92851e50c)

**Additional context**
Below is my docker-compose.yml. This is almost 100% the same as the [copy provided in the Checkmate docs](https://raw.githubusercontent.com/bluewave-labs/Checkmate/refs/heads/master/docker/dist/docker-compose.yaml), I only modified it to change the Client external port to 82 so that it wont clash with other services I'm running on my docker. Could this be related?

```yml
services:
  client:
    image: ghcr.io/bluewave-labs/checkmate:frontend-dist
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "http://localhost:52345/api/v1"
      UPTIME_APP_CLIENT_HOST: "http://localhost"
    ports:
      - "82:80" # Changed external port so it will not clash with other services.
      - "443:443"
    depends_on:
      - server
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist
    restart: always
    ports:
      - "52345:52345"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=http://localhost
      - JWT_SECRET=mysecret
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: ghcr.io/bluewave-labs/checkmate:redis-dist
    restart: always
    volumes:
      - /root/docker/checkpoint/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: ghcr.io/bluewave-labs/checkmate:mongo-dist
    restart: always
    volumes:
      - /root/docker/checkpoint/mongo/data:/data/db
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
```
