### ISSUE TITLE
Unable to resolve domains behind local DNS server

### ISSUE THREAD

**Issue by iComputerfreak** [bluewave-labs/Checkmate#2490]
**Describe the bug**
I have set up Checkmate behind a Traefik reverse proxy using this docker compose file:

```yaml
services:
  server:
    image: ghcr.io/bluewave-labs/checkmate:backend-dist-mono-multiarch
    restart: unless-stopped
    ports:
      - "52345:52345"
    environment:
      - UPTIME_APP_API_BASE_URL=https://example.org/api/v1
      - UPTIME_APP_CLIENT_HOST=https://example.org
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
      - CLIENT_HOST=https://example.org
      - JWT_SECRET=MY_RANDOM_PASSWORD
      - TOKEN_TTL=30d
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:7
    container_name: checkmate-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.18
    container_name: checkmate-mongodb
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
  mongo-init:
    image: mongo:4.4.18
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to be ready...' &&
        until mongo --host mongodb --eval 'db.adminCommand(\"ping\")' > /dev/null 2>&1; do
          sleep 2
        done &&
        echo 'MongoDB is up. Initiating replica set...' &&
        mongo --host mongodb --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongodb:27017\" }]
          })
        ' || echo 'Replica set may already be initialized.'
      "
```

`example.org` is the domain that my local DNS points to the corresponding host where Traefik is installed, which in turn proxies it to the Raspberry Pi on which I installed checkmate.

So far, this all works. I can reach Checkmate, log in, create uptime monitors and everything.

The issues come when I try to monitor one of my internal services (which itself is also behind a Traefik reverse proxy). The monitoring returns error 5000 "network error" and the docker logs show the following error message:

```
2025-06-18T18:31:24.799Z error: [monitorController](getMonitorCertificate) getaddrinfo ENOTFOUND subdomain.example.org (stack: [
  {
    "function": "GetAddrInfoReqWrap.onlookupall [as oncomplete]",
    "file": "node:dns",
    "line": 120,
    "column": 26
  }
])
```

As far as I understood it, the docker service should use the same DNS server as its host, which is my local DNS server that holds the entry for `subdomain.example.org`, but for some reason it seems it doesn't. I also tried setting a custom DNS server in the docker compose, by adding `dns: my.dns.ip.cidr` to the `server` service in the docker compose, but this doesn't seem to work either.

On my Raspberry Pi host directly, I can query the subdomain with `wget` without issues, but when I exec into the docker container, `wget` fails with "bad address".

Monitoring public sites (e.g., Google) works without issues and the subdomain I'm trying to monitor is also reachable on my client machine that I use to access Checkmate.

**To Reproduce**
1. Install Checkmate on a Raspberry Pi using the docker-compose.yml above
2. Create a monitor for a HTTPS website that is only reachable via the local DNS server
3. **The status check fails with a network error**

**Expected behavior**
The docker container should use the local DNS server (in this case docker's 127.0.0.11, which delegates to the host's DNS server) to make the status monitoring checks.

**Screenshots**

<img width="1368" alt="Image" src="https://github.com/user-attachments/assets/0158262f-ab85-4661-8d67-d67767206c84" />

**Desktop (please complete the following information):**
 - Browser: Safari
 - Version: 18.5 (20621.2.5.11.8)

If you need any more information or have any ideas what else I could try, please let me know.

**Comment by gorkem-bwl** [comment]
I am not an expert here but pasted your findings to ChatGPT and asked to come up with a response. The answers seemed to be quite valid to me. Maybe you can also try? :)

**Comment by iComputerfreak** [comment]
I tried before posting here, but unfortunately ChatGPT seems to be not really helpful here. It suggests three options for me.

1. **Explicitly set the DNS server in your Docker Compose file**: I already tried that, but it didn't work. Also ChatGPTs suggestion, that the docker container does not by default use the host's DNS server seems wrong, as it works without issues for other docker containers.
2. **Use extra_hosts to force DNS mapping**: This is not feasible for me, as I would need to manually set all DNS entries in the compose file and restart the container each time.
3. **Bind host /etc/resolv.conf into container**: This would mean that I can no longer use `mongodb` and `redis` as hostnames for the other two services and would need to configure their networks manually. I haven't tried this, but it also seems like a workaround solution that I'm not sure will work, as the DNS resolving works for other services (e.g., Uptime Kuma running on the same host) without issues.

**Comment by gorkem-bwl** [comment]
Ok, let's keep this issue open and see if someone would respond to this, as it is a config issue to me. If there is a fix for this and we need to make changes in the config file(s) for others to properly do the same, we can do that.

**Comment by ajhollid** [comment]
Hi @iComputerfreak ,

That error in your logs is related to a request to fetch SSL certificate info, it's not directly related to monitoring.  Do you have any other error logs that you can share that might help shed light on the problem?

You're correct Docker will use the host DNS server by default, and you've also treid to explicitly set the DNS server so that may not be the issue.

**Comment by iComputerfreak** [comment]
Hi @ajhollid,

I set the log level to debug, but unfortunately the message I posted above is the only message in relation to this error that is posted into the docker log. Other than that I only see worker uptime messages and buffer flushes, all info or debug level.

As for the SSL certificate, I use Traefik to provide Let's Encrypt wildcard certificates for the domain I am monitoring. Could it be an issue that Checkmate doesn't like the wildcard certificate? I have heard before that they can cause issues in some cases.

I also remembered that the two services I tried to monitor are secured by Authelia middleware and tried with another service that has no middleware, but I get the same issues there. Enabling the option in Checkmate to "Ignore SSL/TLS errors" also does not help.

The SSL certificate is also shown as a trusted Let's Encrypt wildcard certificate in my browser for the website I'm trying to monitor.

**Comment by ajhollid** [comment]
Hi @iComputerfreak ,

I don't believe this is an issue with certificates, it appears that the problem is that checkmate cannot resolve the address it has been given.

What you can do is log in to your checkmate server container

`docker exec -it <container_id> /bin/sh`

and take a look at `resolve.conf` by running `cat  /etc/resolv.conf` and see what's going on there.  If docker's nameserver is not poinitng to your local DNS server, therein lies the issue I would think.

For example you can see that my container is pointing to my host nameserver as expected

```
nameserver 127.0.0.11
options edns0 trust-ad ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [host(127.0.0.53)]
# Overrides: []
# Option ndots from: internal
```

**Comment by iComputerfreak** [comment]
Hi @ajhollid,
this is my `/etc/resolv.conf` of the `checkmate-server` container. To me it looks like it's correctly pointing to my DNS server on `10.0.2.168`.

```
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 127.0.0.11
search fritz.box
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [host(10.0.2.168) host(2a02:8071:7102:5480:be24:11ff:febb:4731)]
# Overrides: []
# Option ndots from: internal
```

**Comment by ajhollid** [comment]
> Hi @ajhollid,
> this is my `/etc/resolv.conf` of the `checkmate-server` container. To me it looks like it's correctly pointing to my DNS server on `10.0.2.168`.
> 
> ```
> # Generated by Docker Engine.
> # This file can be edited; Docker Engine will not make further changes once it
> # has been modified.
> 
> nameserver 127.0.0.11
> search fritz.box
> options ndots:0
> 
> # Based on host file: '/etc/resolv.conf' (internal resolver)
> # ExtServers: [host(10.0.2.168) host(2a02:8071:7102:5480:be24:11ff:febb:4731)]
> # Overrides: []
> # Option ndots from: internal
> ```

Yes that looks exactly as I'd expect 🤔

Can you reach your service from the container with `wget`?

If you can, then we know the problem is on the checkmate side, if not, then it's something to do with docker network.

**Comment by iComputerfreak** [comment]
No. `nslookup` works, but `wget` fails with a "bad address" error.

I would try `curl` with a more verbose mode, but I don't know how to install it without `apt` being available inside the container.

**Comment by ajhollid** [comment]
> No. `nslookup` works, but `wget` fails with a "bad address" error.
> 
> I would try `curl` with a more verbose mode, but I don't know how to install it without `apt` being available inside the container.

You could try spinning up a more full featured container and testing from there, one that has `curl` and `dig`

**Comment by iComputerfreak** [comment]
I tried `curl` in another container, but there it is able to resolve the domain without issues. In general, checkmate is the only container I have had issues with DNS resolving so far.

**Comment by ajhollid** [comment]
> I tried `curl` in another container, but there it is able to resolve the domain without issues. In general, checkmate is the only container I have had issues with DNS resolving so far.

Hmm interesting 🤔

I wish I was able to replicate your setup to figure out what's going on.

I'll try to set up a nameserver when I find some time tine to dig further.

You could try building Checkmate with a different base image and see if that helps 🤔

**Comment by iComputerfreak** [comment]
Hm, I think that is too much effort for me. I think in this case I will look for an alternative monitoring solution.

But thank you for trying to help.

**Comment by TheSilentOn3** [comment]
I know it's an old thread, maybe this will help you. I also had to point my container's DNS to my Adguard instance by specifying it in the compose file. 
```
services:
  server:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono-multiarch:latest
    restart: always
    ports:
      - "52345:52345"
    dns:
      - 192.168.0.1  # Replace with your desired DNS server IP
```
